### PR TITLE
Only keep variables as keys in the unroller cache

### PR DESCRIPTION
**Pull request by makaimann**
All right, so @lonsing and I, with lots of help from the boolector developers have been looking into https://github.com/upscale-project/cosa2/issues/36. We're pretty sure that it happens because the boolector `nodemap` which is used in `smt-switch` for the `substitute` function only supports variable -> term substitutions. Because we use the cache in `substitute` in the unroller, this could add non-variables as keys which could cause problems. I added an assertion checking this in `smt-switch` and then made this change so that the cache is always over variables.

Note, one alternative is to not use `nodemap` for substitution, instead relying on the `smt-switch` implementation of `substitute`. However, I would expect that to be much slower because it involves unpacking all the wrapped objects at each subterm. I think the main purpose of the cache was for quick look ups of variables (which still happens), so this fix makes sense to me. What do you guys think?

@lonsing would it be difficult for you to port this change to your setup for reproducing the bug and make sure that it fixes it there also? I checked using the latest versions of everything.

### CODE REVIEW

**Comment by ahmed-irfan** [comment]
here is the PR I mentioned earlier https://github.com/upscale-project/cosa2/pull/42

**Comment by ahmed-irfan** [comment]
can we run an experiment using the competition benchmarks?

**Comment by makaimann** [comment]
Yeah that's a good idea. I'm still going to merge this now though because this still fixes a bug. But we can run experiments to see how much it affects performance.

**Comment by makaimann** [comment]
It looks like we pick up a few more benchmarks overall -- but it's not a huge difference.

The hwmcc19 "practice" benchmarks:

Screen Shot 2020-06-08 at 11 24 50 AM

Screen Shot 2020-06-08 at 11 26 29 AM

Benchmarks from the POR TACAS paper. Only comparing BMC because these are all false.
Screen Shot 2020-06-08 at 11 27 42 AM

**Pull request merged**
